name: fresh_fashion_mobile
description: "Fresh Fashion Mobile"

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  intl: ^0.19.0
  flutter_localization: ^0.2.2
  web: ^1.0.0
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.15
  either_dart: ^1.0.0
  package_info_plus: ^8.1.1
  url_launcher: ^6.3.1
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animation/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - .env

  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
  generate: true